-- Patente B vocabulary seed (sections 1-3)
-- Section 1: La Strada e i Veicoli
INSERT INTO public.vocabulary (word_it, translation_en, translation_bn) VALUES
('carreggiata', 'carriageway', 'সড়ক চলাচল অংশ'),
('corsia', 'lane', 'লেন'),
('banchina', 'road shoulder', 'সড়কের কাঁধ'),
('marciapiede', 'sidewalk', 'ফুটপাত'),
('spartitraffico', 'median', 'মাঝখানের বিভাজক'),
('intersezione', 'intersection', 'ইন্টারসেকশন'),
('incrocio', 'crossroad', 'রাস্তার মোড়'),
('rotonda', 'roundabout', 'গোলচত্বর'),
('svincolo', 'interchange', 'ইন্টারচেঞ্জ'),
('rampa', 'ramp', 'র‌্যাম্প'),
('cavalcavia', 'overpass', 'উপরি সেতু'),
('sottopasso', 'underpass', 'আন্ডারপাস'),
('ponte', 'bridge', 'সেতু'),
('galleria', 'tunnel', 'টানেল'),
('autostrada', 'motorway', 'মোটরওয়ে'),
('superstrada', 'expressway', 'এক্সপ্রেসওয়ে'),
('strada statale', 'state road', 'জাতীয় সড়ক'),
('strada provinciale', 'provincial road', 'প্রাদেশিক সড়ক'),
('strada comunale', 'municipal road', 'পৌর সড়ক'),
('strada urbana', 'urban road', 'শহুরে সড়ক'),
('strada extraurbana', 'rural road', 'শহরতলির সড়ক'),
('zona pedonale', 'pedestrian zone', 'পদচারী এলাকা'),
('area pedonale', 'pedestrian area', 'পদচারী এলাকা'),
('pista ciclabile', 'cycle path', 'সাইকেল পথ'),
('corsia ciclabile', 'cycle lane', 'সাইকেল লেন'),
('attraversamento pedonale', 'pedestrian crossing', 'পদচারী পারাপার'),
('attraversamento ciclabile', 'cycle crossing', 'সাইকেল পারাপার'),
('area di sosta', 'rest area', 'বিশ্রাম এলাকা'),
('area di servizio', 'service area', 'সার্ভিস এলাকা'),
('piazzola di sosta', 'pull-off bay', 'থামার বে'),
('corsia di emergenza', 'emergency lane', 'জরুরি লেন'),
('corsia di accelerazione', 'acceleration lane', 'ত্বরণ লেন'),
('corsia di decelerazione', 'deceleration lane', 'হ্রাস লেন'),
('corsia riservata', 'reserved lane', 'সংরক্ষিত লেন'),
('corsia di marcia', 'travel lane', 'চলাচল লেন'),
('senso unico', 'one-way', 'একদিক রাস্তা'),
('doppio senso', 'two-way', 'দুইদিক রাস্তা'),
('ciclomotore', 'moped', 'মোপেড'),
('motociclo', 'motorcycle', 'মোটরসাইকেল'),
('autovettura', 'passenger car', 'যাত্রীবাহী গাড়ি'),
('autocarro', 'truck', 'ট্রাক'),
('autobus', 'bus', 'বাস'),
('autocaravan', 'motor caravan', 'মোটর ক্যারাভ্যান'),
('rimorchio', 'trailer', 'ট্রেলার'),
('semirimorchio', 'semitrailer', 'সেমিট্রেলার');

-- Section 2: Segnaletica Verticale
INSERT INTO public.vocabulary (word_it, translation_en, translation_bn) VALUES
('segnale di pericolo', 'warning sign', 'বিপদ সংকেত'),
('segnale di prescrizione', 'regulatory sign', 'বাধ্যতামূলক সংকেত'),
('segnale di divieto', 'prohibitory sign', 'নিষেধাজ্ঞা সংকেত'),
('segnale di obbligo', 'mandatory sign', 'বাধ্যতামূলক সংকেত'),
('segnale di precedenza', 'priority sign', 'অগ্রাধিকার সংকেত'),
('segnale di indicazione', 'information sign', 'তথ্য সংকেত'),
('dare precedenza', 'give way', 'অগ্রাধিকার দিতে হবে'),
('stop', 'stop', 'থামো'),
('precedenza', 'priority', 'অগ্রাধিকার'),
('senso vietato', 'no entry', 'প্রবেশ নিষেধ'),
('divieto di transito', 'no through traffic', 'চলাচল নিষেধ'),
('divieto di sorpasso', 'no overtaking', 'ওভারটেক নিষেধ'),
('divieto di fermata', 'no stopping', 'থামা নিষেধ'),
('divieto di sosta', 'no parking', 'পার্কিং নিষেধ'),
('limite di velocita', 'speed limit', 'গতিসীমা'),
('fine limite di velocita', 'end of speed limit', 'গতিসীমা সমাপ্তি'),
('obbligo di svolta a destra', 'mandatory right turn', 'ডানদিকে বাধ্যতামূলক মোড়'),
('obbligo di svolta a sinistra', 'mandatory left turn', 'বামদিকে বাধ্যতামূলক মোড়'),
('passaggio obbligatorio', 'mandatory direction', 'বাধ্যতামূলক দিক'),
('rotatoria obbligatoria', 'mandatory roundabout', 'গোলচত্বরে চলা বাধ্যতামূলক'),
('obbligo di catene', 'snow chains mandatory', 'চেইন বাধ্যতামূলক'),
('obbligo di uso casco', 'helmet mandatory', 'হেলমেট বাধ্যতামূলক'),
('obbligo di cinture', 'seatbelts mandatory', 'সিটবেল্ট বাধ্যতামূলক'),
('strada prioritaria', 'priority road', 'অগ্রাধিকার সড়ক'),
('fine strada prioritaria', 'end of priority road', 'অগ্রাধিকার সড়ক সমাপ্তি'),
('incrocio con precedenza', 'priority junction', 'অগ্রাধিকার সংযোগস্থল'),
('passaggio a livello', 'level crossing', 'রেলক্রসিং'),
('passaggio a livello senza barriere', 'level crossing without barriers', 'বাধাহীন রেলক্রসিং'),
('passaggio a livello con barriere', 'level crossing with barriers', 'বাধাযুক্ত রেলক্রসিং'),
('curva pericolosa', 'dangerous bend', 'বিপজ্জনক বাঁক'),
('doppia curva', 'double bend', 'দ্বৈত বাঁক'),
('dosso', 'speed bump', 'গতির ঢাল'),
('cunetta', 'dip', 'খাদ'),
('strada sdrucciolevole', 'slippery road', 'পিচ্ছিল রাস্তা'),
('caduta massi', 'falling rocks', 'পাথর ধস'),
('attraversamento pedonale', 'pedestrian crossing sign', 'পদচারী পারাপার সংকেত'),
('attraversamento ciclabile', 'cycle crossing sign', 'সাইকেল পারাপার সংকেত'),
('bambini', 'children crossing', 'শিশু পারাপার'),
('lavori in corso', 'roadworks', 'সড়ককর্ম'),
('strettoia', 'road narrows', 'রাস্তা সংকীর্ণ'),
('strettoia asimmetrica', 'asymmetric narrowing', 'একপাশে সংকীর্ণ'),
('vento laterale', 'crosswind', 'পার্শ্ব বায়ু'),
('doppio senso di circolazione', 'two-way traffic', 'দুইমুখী চলাচল'),
('fine divieto di sorpasso', 'end of no overtaking', 'ওভারটেক নিষেধ সমাপ্তি'),
('fine obbligo', 'end of mandatory', 'বাধ্যতামূলক সমাপ্তি'),
('direzione obbligatoria a destra', 'mandatory direction right', 'ডানদিকে বাধ্যতামূলক দিক'),
('direzione obbligatoria a sinistra', 'mandatory direction left', 'বামদিকে বাধ্যতামূলক দিক');

-- Section 3: Segnaletica Orizzontale e Luminosa
INSERT INTO public.vocabulary (word_it, translation_en, translation_bn) VALUES
('striscia longitudinale', 'longitudinal line', 'দীর্ঘায়ত রেখা'),
('striscia continua', 'continuous line', 'অবিচ্ছিন্ন রেখা'),
('striscia discontinua', 'broken line', 'ভাঙা রেখা'),
('doppia striscia continua', 'double continuous line', 'দ্বৈত অবিচ্ছিন্ন রেখা'),
('striscia mista', 'combination line', 'মিশ্র রেখা'),
('linea di margine', 'edge line', 'প্রান্তরেখা'),
('linea di corsia', 'lane line', 'লেন রেখা'),
('linea di arresto', 'stop line', 'থামার রেখা'),
('linea di dare precedenza', 'give way line', 'অগ্রাধিকার দেওয়ার রেখা'),
('zebratura', 'chevron marking', 'জেব্রা চিহ্ন'),
('isola di traffico', 'traffic island', 'ট্রাফিক আইল্যান্ড'),
('attraversamento pedonale', 'pedestrian crossing', 'পদচারী পারাপার'),
('attraversamento ciclabile', 'cycle crossing', 'সাইকেল পারাপার'),
('freccia direzionale', 'directional arrow', 'দিক নির্দেশক তীর'),
('scritta orizzontale', 'road marking text', 'সড়ক লিখন'),
('linea di mezzeria', 'center line', 'মধ্যরেখা'),
('linea di stop', 'stop line', 'থামার রেখা'),
('linea di guida', 'guidance line', 'নির্দেশনা রেখা'),
('linea di canalizzazione', 'channelizing line', 'চ্যানেলাইজিং রেখা'),
('cordolo', 'kerb', 'কার্ব'),
('rallentatore', 'speed reducer', 'গতিনিয়ন্ত্রক'),
('dosso artificiale', 'speed hump', 'কৃত্রিম ঢাল'),
('semaforo', 'traffic light', 'ট্রাফিক সিগন্যাল'),
('luce rossa', 'red light', 'লাল বাতি'),
('luce gialla', 'amber light', 'হলুদ বাতি'),
('luce verde', 'green light', 'সবুজ বাতি'),
('luce gialla intermittente', 'flashing amber light', 'ঝলমলে হলুদ বাতি'),
('luce rossa lampeggiante', 'flashing red light', 'ঝলমলে লাল বাতি'),
('semaforo pedonale', 'pedestrian signal', 'পদচারী সিগন্যাল'),
('semaforo a freccia', 'arrow signal', 'তীর সিগন্যাল'),
('lanterna semaforica', 'signal head', 'সিগন্যাল লাইট ইউনিট'),
('polizia stradale', 'traffic police', 'ট্রাফিক পুলিশ'),
('segnale luminoso', 'light signal', 'আলোক সংকেত'),
('paletta', 'police paddle', 'পুলিশের প্যাডল'),
('fischio', 'whistle signal', 'শিস সংকেত'),
('braccio teso', 'outstretched arm', 'প্রসারিত বাহু'),
('braccio alzato', 'raised arm', 'উঁচু করা বাহু'),
('segnale manuale', 'hand signal', 'হাতের সংকেত'),
('segnale acustico', 'audible signal', 'শব্দ সংকেত'),
('corsia reversibile', 'reversible lane', 'দিক পরিবর্তনশীল লেন'),
('segnale di corsia', 'lane control signal', 'লেন নিয়ন্ত্রণ সংকেত'),
('via libera', 'proceed', 'চলুন'),
('arresto obbligatorio', 'mandatory stop', 'বাধ্যতামূলক থামা'),
('lampeggiante', 'flashing beacon', 'ঝলমলে বীকন');

-- Section 4: Norme di Precedenza
INSERT INTO public.vocabulary (word_it, translation_en, translation_bn) VALUES
('precedenza a destra', 'priority to the right', 'ডানদিকের অগ্রাধিকার'),
('diritto di precedenza', 'right of way', 'অগ্রাধিকার অধিকার'),
('cedere il passo', 'yield', 'পথ ছেড়ে দেওয়া'),
('incrocio non regolato', 'uncontrolled junction', 'নিয়ন্ত্রণহীন সংযোগস্থল'),
('incrocio regolato', 'controlled junction', 'নিয়ন্ত্রিত সংযোগস্থল'),
('semaforo', 'traffic light', 'ট্রাফিক সিগন্যাল'),
('agente del traffico', 'traffic officer', 'ট্রাফিক কর্মকর্তা'),
('precedenza obbligatoria', 'mandatory priority', 'বাধ্যতামূলক অগ্রাধিকার'),
('precedenza alternata', 'alternating priority', 'পর্যায়ক অগ্রাধিকার'),
('intersezione a raso', 'at-grade intersection', 'সমতল সংযোগস্থল'),
('intersezione a livelli sfalsati', 'grade-separated intersection', 'স্তর পৃথক সংযোগস্থল'),
('rotatoria', 'roundabout', 'গোলচত্বর'),
('immissione', 'entry', 'প্রবেশ'),
('uscita', 'exit', 'প্রস্থান'),
('confluenza', 'merge', 'মার্জ'),
('immissione in autostrada', 'motorway entry', 'মোটরওয়ে প্রবেশ'),
('immissione da rampa', 'ramp entry', 'র‌্যাম্প থেকে প্রবেশ'),
('corsia di accelerazione', 'acceleration lane', 'ত্বরণ লেন'),
('corsia di decelerazione', 'deceleration lane', 'হ্রাস লেন'),
('svolta a destra', 'right turn', 'ডান মোড়'),
('svolta a sinistra', 'left turn', 'বাম মোড়'),
('inversione di marcia', 'u-turn', 'ইউ-টার্ন'),
('attraversamento', 'crossing', 'পারাপার'),
('attraversamento pedonale', 'pedestrian crossing', 'পদচারী পারাপার'),
('attraversamento ciclabile', 'cycle crossing', 'সাইকেল পারাপার'),
('passaggio a livello', 'level crossing', 'রেলক্রসিং'),
('precedenza ai tram', 'priority to trams', 'ট্রামের অগ্রাধিকার'),
('precedenza ai pedoni', 'priority to pedestrians', 'পদচারীর অগ্রাধিকার'),
('precedenza ai veicoli di soccorso', 'priority to emergency vehicles', 'জরুরি যানবাহনের অগ্রাধিকার'),
('precedenza ai veicoli su rotaia', 'priority to rail vehicles', 'রেলযানের অগ্রাধিকার'),
('precedenza in rotatoria', 'roundabout priority', 'গোলচত্বরে অগ্রাধিকার'),
('precedenza in salita', 'priority uphill', 'ঢালু পথে অগ্রাধিকার'),
('precedenza in discesa', 'priority downhill', 'ঢাল বেয়ে অগ্রাধিকার'),
('incrocio a t', 't-junction', 'টি-সংযোগস্থল'),
('incrocio a y', 'y-junction', 'ওয়াই-সংযোগস্থল'),
('intersezione complessa', 'complex intersection', 'জটিল সংযোগস্থল'),
('segnale di stop', 'stop sign', 'স্টপ সংকেত'),
('segnale di dare precedenza', 'give way sign', 'অগ্রাধিকার দিতে হবে সংকেত'),
('intersezione con semaforo', 'signalized intersection', 'সিগন্যালযুক্ত সংযোগস্থল'),
('incrocio con rotatoria', 'roundabout junction', 'গোলচত্বর সংযোগস্থল'),
('strada principale', 'main road', 'প্রধান সড়ক'),
('strada secondaria', 'minor road', 'গৌণ সড়ক'),
('corsia di canalizzazione', 'channelized lane', 'চ্যানেলাইজড লেন'),
('linea di arresto', 'stop line', 'থামার রেখা'),
('linea di dare precedenza', 'give way line', 'অগ্রাধিকার দেওয়ার রেখা'),
('precedenza ai veicoli gia in transito', 'priority to vehicles already in transit', 'আগে চলমান যানবাহনের অগ্রাধিকার');

-- Section 5: Comportamento e Manovre
INSERT INTO public.vocabulary (word_it, translation_en, translation_bn) VALUES
('sorpassare', 'overtake', 'ওভারটেক করা'),
('sorpasso', 'overtaking', 'ওভারটেকিং'),
('distanza di sicurezza', 'safety distance', 'নিরাপদ দূরত্ব'),
('velocita', 'speed', 'গতি'),
('limite di velocita', 'speed limit', 'গতিসীমা'),
('frenare', 'brake', 'ব্রেক করা'),
('frenata', 'braking', 'ব্রেকিং'),
('frenata di emergenza', 'emergency braking', 'জরুরি ব্রেকিং'),
('accelerare', 'accelerate', 'ত্বরণ করা'),
('decelerare', 'decelerate', 'গতি কমানো'),
('cambiare corsia', 'change lane', 'লেন পরিবর্তন করা'),
('immettersi', 'merge', 'মার্জ করা'),
('svoltare', 'turn', 'মোড় নেওয়া'),
('invertire la marcia', 'make a u-turn', 'ইউ-টার্ন করা'),
('retrocedere', 'reverse', 'পেছনে যাওয়া'),
('retromarcia', 'reverse gear', 'রিভার্স গিয়ার'),
('partenza', 'starting', 'শুরু'),
('ripartenza', 'restarting', 'পুনরায় শুরু'),
('arrestare', 'stop', 'থামা'),
('arresto', 'stop', 'থামা'),
('fermare', 'stop', 'থামানো'),
('curvare', 'turn', 'বাঁক নেওয়া'),
('curva', 'bend', 'বাঁক'),
('passare', 'pass', 'অতিক্রম করা'),
('superare', 'pass', 'অতিক্রম করা'),
('coda', 'queue', 'সারি'),
('traffico intenso', 'heavy traffic', 'ভারী যান চলাচল'),
('traffico scorrevole', 'free-flow traffic', 'স্বচ্ছন্দ যান চলাচল'),
('guida difensiva', 'defensive driving', 'রক্ষণাত্মক চালনা'),
('guida prudente', 'cautious driving', 'সতর্ক চালনা'),
('guida economica', 'eco-driving', 'সাশ্রয়ী চালনা'),
('attenzione', 'attention', 'সতর্কতা'),
('precedenza', 'priority', 'অগ্রাধিকার'),
('dare precedenza', 'give way', 'অগ্রাধিকার দেওয়া'),
('mantenere la corsia', 'keep lane', 'লেন বজায় রাখা'),
('mantenere la distanza', 'keep distance', 'দূরত্ব বজায় রাখা'),
('segnalare', 'signal', 'সংকেত দেওয়া'),
('indicatore di direzione', 'turn signal', 'টার্ন সিগন্যাল'),
('uso delle luci', 'use of lights', 'লাইট ব্যবহারের নিয়ম'),
('uso del clacson', 'use of horn', 'হর্ন ব্যবহারের নিয়ম'),
('marcia in salita', 'uphill driving', 'উপরের দিকে চালনা'),
('marcia in discesa', 'downhill driving', 'নিচের দিকে চালনা'),
('cambio di direzione', 'change of direction', 'দিক পরিবর্তন'),
('visibilita', 'visibility', 'দৃশ্যমানতা'),
('spazio di frenata', 'braking distance', 'ব্রেকিং দূরত্ব'),
('spazio di arresto', 'stopping distance', 'থামার দূরত্ব'),
('tempo di reazione', 'reaction time', 'প্রতিক্রিয়া সময়');

-- Section 6: Fermata, Sosta e Arresto
INSERT INTO public.vocabulary (word_it, translation_en, translation_bn) VALUES
('fermata', 'stopping', 'থামা'),
('sosta', 'parking', 'পার্কিং'),
('arresto', 'halt', 'সম্পূর্ণ থামা'),
('fermata di emergenza', 'emergency stop', 'জরুরি থামা'),
('sosta vietata', 'parking prohibited', 'পার্কিং নিষেধ'),
('fermata vietata', 'stopping prohibited', 'থামা নিষেধ'),
('sosta consentita', 'parking allowed', 'পার্কিং অনুমোদিত'),
('sosta a tempo', 'time-limited parking', 'সময় সীমিত পার্কিং'),
('sosta regolamentata', 'regulated parking', 'নিয়ন্ত্রিত পার্কিং'),
('sosta su carreggiata', 'parking on roadway', 'রাস্তার উপর পার্কিং'),
('sosta su marciapiede', 'parking on sidewalk', 'ফুটপাতে পার্কিং'),
('sosta in doppia fila', 'double parking', 'ডাবল পার্কিং'),
('sosta in area privata', 'private area parking', 'ব্যক্তিগত এলাকায় পার্কিং'),
('sosta negli stalli', 'parking in bays', 'পার্কিং বেতে থামা'),
('stalli di sosta', 'parking bays', 'পার্কিং বে'),
('parcheggio', 'parking lot', 'পার্কিং এলাকা'),
('parcheggio pubblico', 'public parking', 'সরকারি পার্কিং'),
('parcheggio privato', 'private parking', 'ব্যক্তিগত পার্কিং'),
('parcheggio a pagamento', 'paid parking', 'পেইড পার্কিং'),
('parcheggio gratuito', 'free parking', 'ফ্রি পার্কিং'),
('disco orario', 'parking disc', 'পার্কিং ডিস্ক'),
('zona rimozione', 'tow-away zone', 'টো-অ্যাওয়ে এলাকা'),
('rimozione forzata', 'forced removal', 'বাধ্যতামূলক অপসারণ'),
('sosta di carico e scarico', 'loading/unloading stop', 'লোডিং-আনলোডিং থামা'),
('passo carrabile', 'driveway', 'ড্রাইভওয়ে'),
('fermata autobus', 'bus stop', 'বাস স্টপ'),
('fermata tram', 'tram stop', 'ট্রাম স্টপ'),
('fermata taxi', 'taxi stand', 'ট্যাক্সি স্ট্যান্ড'),
('fermata scuolabus', 'school bus stop', 'স্কুল বাস স্টপ'),
('sosta in curva', 'parking on bend', 'বাঁকে পার্কিং'),
('sosta in prossimita di incrocio', 'parking near junction', 'সংযোগস্থলের কাছে পার্কিং'),
('sosta davanti a passo carrabile', 'parking in front of driveway', 'ড্রাইভওয়ের সামনে পার্কিং'),
('sosta vicino a segnale', 'parking near sign', 'সংকেতের কাছে পার্কিং'),
('sosta in galleria', 'parking in tunnel', 'টানেলে পার্কিং'),
('sosta in ponte', 'parking on bridge', 'সেতুতে পার্কিং'),
('sosta in corsia di emergenza', 'parking in emergency lane', 'জরুরি লেনে পার্কিং'),
('sosta in seconda fila', 'parking in second row', 'দ্বিতীয় সারিতে পার্কিং'),
('sosta nei pressi del passaggio a livello', 'parking near level crossing', 'রেলক্রসিংয়ের কাছে পার্কিং'),
('sosta nei pressi del semaforo', 'parking near traffic light', 'সিগন্যালের কাছে পার্কিং'),
('sosta nei pressi del passaggio pedonale', 'parking near pedestrian crossing', 'পদচারী পারাপারের কাছে পার্কিং'),
('fermata breve', 'brief stop', 'স্বল্প থামা'),
('sosta prolungata', 'long parking', 'দীর্ঘ পার্কিং'),
('arresto del veicolo', 'vehicle halt', 'যানবাহন থামা');

-- Section 7: Il Veicolo a Motore
INSERT INTO public.vocabulary (word_it, translation_en, translation_bn) VALUES
('motore', 'engine', 'ইঞ্জিন'),
('cilindro', 'cylinder', 'সিলিন্ডার'),
('pistone', 'piston', 'পিস্টন'),
('albero motore', 'crankshaft', 'ক্র্যাঙ্কশ্যাফট'),
('albero a camme', 'camshaft', 'ক্যামশ্যাফট'),
('frizione', 'clutch', 'ক্লাচ'),
('cambio', 'gearbox', 'গিয়ারবক্স'),
('marcia', 'gear', 'গিয়ার'),
('trasmissione', 'transmission', 'ট্রান্সমিশন'),
('differenziale', 'differential', 'ডিফারেনশিয়াল'),
('impianto frenante', 'braking system', 'ব্রেকিং সিস্টেম'),
('freno', 'brake', 'ব্রেক'),
('freno di servizio', 'service brake', 'সার্ভিস ব্রেক'),
('freno di stazionamento', 'parking brake', 'পার্কিং ব্রেক'),
('freno a mano', 'handbrake', 'হ্যান্ডব্রেক'),
('abs', 'abs', 'এবিএস'),
('pastiglia', 'brake pad', 'ব্রেক প্যাড'),
('disco freno', 'brake disc', 'ব্রেক ডিস্ক'),
('tamburo', 'brake drum', 'ব্রেক ড্রাম'),
('pneumatico', 'tire', 'টায়ার'),
('battistrada', 'tread', 'ট্রেড'),
('pressione', 'pressure', 'চাপ'),
('ruota', 'wheel', 'চাকা'),
('cerchio', 'rim', 'রিম'),
('sospensione', 'suspension', 'সাসপেনশন'),
('ammortizzatore', 'shock absorber', 'শক অ্যাবজরবার'),
('sterzo', 'steering', 'স্টিয়ারিং'),
('volante', 'steering wheel', 'স্টিয়ারিং হুইল'),
('servosterzo', 'power steering', 'পাওয়ার স্টিয়ারিং'),
('faro', 'headlight', 'হেডলাইট'),
('anabbagliante', 'low beam', 'লো বিম'),
('abbagliante', 'high beam', 'হাই বিম'),
('luce di posizione', 'position light', 'পজিশন লাইট'),
('luce di stop', 'brake light', 'ব্রেক লাইট'),
('indicatore di direzione', 'turn indicator', 'টার্ন ইন্ডিকেটর'),
('luce retronebbia', 'rear fog light', 'রিয়ার ফগ লাইট'),
('luce anteriore', 'front light', 'সামনের লাইট'),
('specchietto', 'mirror', 'আয়না'),
('specchietto retrovisore', 'rear-view mirror', 'রিয়ার-ভিউ আয়না'),
('parabrezza', 'windshield', 'উইন্ডশিল্ড'),
('tergicristallo', 'wiper', 'ওয়াইপার'),
('cintura di sicurezza', 'seat belt', 'সিট বেল্ট'),
('airbag', 'airbag', 'এয়ারব্যাগ'),
('carrozzeria', 'bodywork', 'গাড়ির বডি'),
('telaio', 'chassis', 'চ্যাসিস'),
('marmitta', 'exhaust', 'এক্সহস্ট'),
('scarico', 'exhaust', 'এক্সহস্ট'),
('radiatore', 'radiator', 'রেডিয়েটর'),
('liquido di raffreddamento', 'coolant', 'কুল্যান্ট'),
('batteria', 'battery', 'ব্যাটারি');

-- Section 8: Documenti e Responsabilita
INSERT INTO public.vocabulary (word_it, translation_en, translation_bn) VALUES
('patente di guida', 'driving license', 'ড্রাইভিং লাইসেন্স'),
('foglio rosa', 'learner permit', 'লার্নার পারমিট'),
('carta di circolazione', 'registration certificate', 'রেজিস্ট্রেশন সার্টিফিকেট'),
('certificato di proprieta', 'certificate of ownership', 'মালিকানা সনদ'),
('assicurazione', 'insurance', 'বিমা'),
('responsabilita civile', 'civil liability', 'দেওয়ানি দায়'),
('responsabilita penale', 'criminal liability', 'ফৌজদারি দায়'),
('revisione', 'inspection', 'পরিদর্শন'),
('collaudo', 'technical test', 'কারিগরি পরীক্ষা'),
('tassa di possesso', 'vehicle tax', 'যানবাহন কর'),
('bollo', 'vehicle tax stamp', 'বলো কর'),
('multa', 'fine', 'জরিমানা'),
('sanzione', 'sanction', 'দণ্ড'),
('decurtazione punti', 'points deduction', 'পয়েন্ট কর্তন'),
('punteggio', 'points', 'পয়েন্ট'),
('limite di punti', 'points limit', 'পয়েন্ট সীমা'),
('ricorso', 'appeal', 'আপিল'),
('sospensione della patente', 'license suspension', 'লাইসেন্স স্থগিত'),
('revoca della patente', 'license revocation', 'লাইসেন্স বাতিল'),
('sequestro', 'seizure', 'জব্দ'),
('fermo amministrativo', 'administrative stop', 'প্রশাসনিক স্থগিত'),
('confisca', 'confiscation', 'বাজেয়াপ্ত'),
('verbale', 'ticket report', 'চালান'),
('infrazione', 'violation', 'লঙ্ঘন'),
('assicurazione obbligatoria', 'mandatory insurance', 'বাধ্যতামূলক বিমা'),
('copertura assicurativa', 'insurance coverage', 'বিমা কভারেজ'),
('massimale', 'coverage limit', 'কভারেজ সীমা'),
('sinistro', 'accident', 'দুর্ঘটনা'),
('risarcimento', 'compensation', 'ক্ষতিপূরণ'),
('denuncia', 'report', 'অভিযোগ'),
('patente a punti', 'points-based license', 'পয়েন্টভিত্তিক লাইসেন্স'),
('esame teorico', 'theory exam', 'তত্ত্বীয় পরীক্ষা'),
('esame pratico', 'practical exam', 'ব্যবহারিক পরীক্ষা'),
('visita medica', 'medical check', 'চিকিৎসা পরীক্ষা'),
('idoneita', 'fitness', 'যোগ্যতা'),
('documento di identita', 'identity document', 'পরিচয়পত্র'),
('certificato medico', 'medical certificate', 'মেডিক্যাল সার্টিফিকেট'),
('copertura rca', 'third-party liability coverage', 'থার্ড পার্টি বিমা'),
('targa', 'license plate', 'নম্বর প্লেট'),
('libretto', 'vehicle booklet', 'ভেহিকল বুকলেট'),
('omologazione', 'type approval', 'টাইপ অনুমোদন'),
('revisionato', 'inspected', 'পরিদর্শিত'),
('immatricolazione', 'registration', 'রেজিস্ট্রেশন');

-- Section 9: Primo Soccorso e Psicologia
INSERT INTO public.vocabulary (word_it, translation_en, translation_bn) VALUES
('primo soccorso', 'first aid', 'প্রথম চিকিৎসা'),
('emergenza', 'emergency', 'জরুরি অবস্থা'),
('numero di emergenza', 'emergency number', 'জরুরি নম্বর'),
('ambulanza', 'ambulance', 'অ্যাম্বুলেন্স'),
('ferito', 'injured person', 'আহত ব্যক্তি'),
('trauma', 'trauma', 'আঘাত'),
('emorragia', 'bleeding', 'রক্তক্ষরণ'),
('frattura', 'fracture', 'ভাঙা হাড়'),
('ustione', 'burn', 'দগ্ধ'),
('shock', 'shock', 'শক'),
('perdita di coscienza', 'loss of consciousness', 'অজ্ঞান হওয়া'),
('rianimazione', 'resuscitation', 'পুনর্জীবন'),
('respirazione', 'breathing', 'শ্বাসপ্রশ্বাস'),
('respirazione artificiale', 'artificial respiration', 'কৃত্রিম শ্বাস'),
('massaggio cardiaco', 'cardiac massage', 'হৃদস্পন্দন ম্যাসাজ'),
('posizione laterale di sicurezza', 'recovery position', 'পাশের নিরাপদ ভঙ্গি'),
('chiamare i soccorsi', 'call for help', 'সাহায্য ডাকা'),
('triangolo di emergenza', 'warning triangle', 'জরুরি ত্রিভুজ'),
('giubbotto riflettente', 'reflective vest', 'প্রতিফলক ভেস্ট'),
('fuoco', 'fire', 'আগুন'),
('estintore', 'fire extinguisher', 'অগ্নিনির্বাপক'),
('incendio', 'fire', 'অগ্নিকাণ্ড'),
('fumo', 'smoke', 'ধোঁয়া'),
('evacuazione', 'evacuation', 'উদ্ধার'),
('pericolo', 'danger', 'বিপদ'),
('rischio', 'risk', 'ঝুঁকি'),
('alcol', 'alcohol', 'অ্যালকোহল'),
('tasso alcolemico', 'blood alcohol level', 'রক্তে অ্যালকোহলের মাত্রা'),
('ebbrezza', 'intoxication', 'মদ্যতা'),
('droghe', 'drugs', 'মাদক'),
('sostanze stupefacenti', 'narcotics', 'মাদকদ্রব্য'),
('sonnolenza', 'drowsiness', 'তন্দ্রা'),
('stanchezza', 'fatigue', 'ক্লান্তি'),
('stress', 'stress', 'স্ট্রেস'),
('disattenzione', 'inattention', 'অমনোযোগ'),
('distrazione', 'distraction', 'বিভ্রান্তি'),
('aggressivita', 'aggressiveness', 'আক্রমণাত্মকতা'),
('ansia', 'anxiety', 'উদ্বেগ'),
('panico', 'panic', 'আতঙ্ক'),
('effetti dell alcol', 'effects of alcohol', 'অ্যালকোহলের প্রভাব'),
('effetti delle droghe', 'effects of drugs', 'মাদকের প্রভাব'),
('riflessi', 'reflexes', 'প্রতিক্রিয়া ক্ষমতা'),
('tempo di reazione', 'reaction time', 'প্রতিক্রিয়া সময়'),
('attenzione alla guida', 'driving attention', 'চালনার মনোযোগ');

-- Section 10: Sicurezza e Inquinamento
INSERT INTO public.vocabulary (word_it, translation_en, translation_bn) VALUES
('sicurezza stradale', 'road safety', 'সড়ক নিরাপত্তা'),
('cintura di sicurezza', 'seat belt', 'সিট বেল্ট'),
('airbag', 'airbag', 'এয়ারব্যাগ'),
('poggiatesta', 'headrest', 'হেডরেস্ট'),
('seggiolino', 'child seat', 'শিশু আসন'),
('casco', 'helmet', 'হেলমেট'),
('giubbotto riflettente', 'reflective vest', 'প্রতিফলক ভেস্ট'),
('triangolo di emergenza', 'warning triangle', 'জরুরি ত্রিভুজ'),
('frecce di emergenza', 'hazard lights', 'হ্যাজার্ড লাইট'),
('frenata controllata', 'controlled braking', 'নিয়ন্ত্রিত ব্রেকিং'),
('frenata progressiva', 'progressive braking', 'ক্রমিক ব্রেকিং'),
('spazio di arresto', 'stopping distance', 'থামার দূরত্ব'),
('spazio di reazione', 'reaction distance', 'প্রতিক্রিয়া দূরত্ব'),
('aderenza', 'road grip', 'গ্রিপ'),
('aquaplaning', 'aquaplaning', 'অ্যাকুয়াপ্ল্যানিং'),
('sovrasterzo', 'oversteer', 'ওভারস্টিয়ার'),
('sottosterzo', 'understeer', 'আন্ডারস্টিয়ার'),
('urto', 'impact', 'আঘাত'),
('collisione', 'collision', 'সংঘর্ষ'),
('zona di assorbimento', 'crumple zone', 'আঘাত শোষণ এলাকা'),
('cellula di sicurezza', 'safety cell', 'নিরাপত্তা কক্ষ'),
('controllo stabilita', 'stability control', 'স্থিতিশীলতা নিয়ন্ত্রণ'),
('controllo trazione', 'traction control', 'ট্র্যাকশন কন্ট্রোল'),
('sicurezza passiva', 'passive safety', 'প্যাসিভ নিরাপত্তা'),
('sicurezza attiva', 'active safety', 'অ্যাকটিভ নিরাপত্তা'),
('visibilita notturna', 'night visibility', 'রাতের দৃশ্যমানতা'),
('abbagliamento', 'glare', 'ঝলক'),
('inquinamento', 'pollution', 'দূষণ'),
('inquinamento atmosferico', 'air pollution', 'বায়ু দূষণ'),
('inquinamento acustico', 'noise pollution', 'শব্দ দূষণ'),
('emissioni', 'emissions', 'নিঃসরণ'),
('gas di scarico', 'exhaust gases', 'এক্সহস্ট গ্যাস'),
('co2', 'co2', 'কার্বন ডাইঅক্সাইড'),
('polveri sottili', 'fine particles', 'সূক্ষ্ম কণা'),
('fumo nero', 'black smoke', 'কালো ধোঁয়া'),
('catalizzatore', 'catalytic converter', 'ক্যাটালাইটিক কনভার্টার'),
('filtro antiparticolato', 'particulate filter', 'পার্টিকুলেট ফিল্টার'),
('risparmio energetico', 'energy saving', 'শক্তি সাশ্রয়'),
('guida ecologica', 'eco-driving', 'পরিবেশবান্ধব চালনা'),
('riduzione consumi', 'fuel saving', 'জ্বালানি সাশ্রয়'),
('rumore', 'noise', 'শব্দ'),
('motore spento', 'engine off', 'ইঞ্জিন বন্ধ'),
('controllo fumi', 'emissions test', 'ধোঁয়া পরীক্ষা'),
('limitazione del traffico', 'traffic restriction', 'ট্রাফিক সীমাবদ্ধতা'),
('zona a traffico limitato', 'limited traffic zone', 'সীমিত যান চলাচল এলাকা'),
('dispositivi di sicurezza', 'safety devices', 'নিরাপত্তা সরঞ্জাম');

-- Tricky Terms: Verbs, Adjectives, Legal, Medical, Technical Nuances
INSERT INTO public.vocabulary (word_it, translation_en, translation_bn) VALUES
('agevolare', 'facilitate', 'সহজ করা'),
('approssimarsi', 'approach', 'নিকটবর্তী হওয়া'),
('intralciare', 'obstruct', 'বাধা সৃষ্টি করা'),
('ingombrare', 'encumber', 'দখল করা'),
('ostacolare', 'hinder', 'বাধাগ্রস্ত করা'),
('arrecare', 'cause', 'সৃষ্টি করা'),
('evitare', 'avoid', 'এড়িয়ে চলা'),
('consentire', 'allow', 'অনুমোদন করা'),
('vietare', 'prohibit', 'নিষেধ করা'),
('obbligare', 'oblige', 'বাধ্য করা'),
('imporre', 'impose', 'আরোপ করা'),
('proibire', 'forbid', 'নিষিদ্ধ করা'),
('omettare', 'omit', 'অবহেলা করা'),
('omologare', 'approve', 'অনুমোদন করা'),
('adeguare', 'adapt', 'মানানসই করা'),
('adeguarsi', 'comply', 'মেনে চলা'),
('mantenere', 'maintain', 'বজায় রাখা'),
('moderare', 'moderate', 'নিয়ন্ত্রণ করা'),
('rallentare', 'slow down', 'গতি কমানো'),
('arrestarsi', 'come to a stop', 'থামা'),
('accertare', 'ascertain', 'যাচাই করা'),
('segnalare', 'signal', 'সংকেত দেওয়া'),
('preavvisare', 'give advance warning', 'পূর্ব সতর্ক করা'),
('sorvegliare', 'monitor', 'নজর রাখা'),
('sorreggere', 'support', 'ধারণ করা'),
('controllare', 'check', 'নিয়ন্ত্রণ করা'),
('supervisionare', 'supervise', 'তদারকি করা'),
('azionare', 'operate', 'চালনা করা'),
('interrompere', 'interrupt', 'বন্ধ করা'),
('proseguire', 'proceed', 'অগ্রসর হওয়া'),
('arrestare', 'stop', 'থামানো'),
('cedere', 'yield', 'অগ্রাধিকার দেওয়া'),
('dare la precedenza', 'give priority', 'অগ্রাধিকার দেওয়া'),
('prestare', 'give', 'প্রদান করা'),
('soccorre', 'aid', 'সহায়তা করা'),
('collaborare', 'cooperate', 'সহযোগিতা করা'),
('rispettare', 'observe', 'মেনে চলা'),
('trascurare', 'neglect', 'অবহেলা করা'),
('infrangere', 'violate', 'লঙ্ঘন করা'),
('violare', 'breach', 'ভঙ্গ করা'),
('rifiutare', 'refuse', 'অস্বীকার করা'),
('esibire', 'produce', 'প্রদর্শন করা'),
('esigere', 'require', 'দাবি করা'),
('sequestrare', 'seize', 'জব্দ করা'),
('revocare', 'revoke', 'বাতিল করা'),
('sospendere', 'suspend', 'স্থগিত করা'),
('sanzionare', 'penalise', 'শাস্তি দেওয়া'),
('ammorbidire', 'reduce', 'হালকা করা'),
('aggravare', 'aggravate', 'বাড়িয়ে দেওয়া'),
('ridurre', 'reduce', 'কমিয়ে আনা'),
('limitare', 'limit', 'সীমাবদ্ধ করা'),
('applicare', 'apply', 'প্রয়োগ করা'),
('consumare', 'consume', 'ব্যয় করা'),
('compiere', 'carry out', 'সম্পাদন করা'),
('aderire', 'adhere', 'অনুসরণ করা'),
('attenersi', 'abide', 'মেনে চলা'),
('inclinare', 'tilt', 'ঢালু করা'),
('sporgere', 'project', 'বাইরে বের হওয়া'),
('illuminare', 'illuminate', 'আলোকিত করা'),
('lampeggiare', 'flash', 'ঝলমল করা'),
('abbagliare', 'dazzle', 'চমকানো'),
('uscire di strada', 'leave the roadway', 'রাস্তা থেকে বের হওয়া'),
('sbandare', 'swerve', 'বাঁকা পথে যাওয়া'),
('slittare', 'skid', 'স্লিপ করা'),
('derapare', 'skid', 'স্কিড করা'),
('urtare', 'hit', 'ধাক্কা দেওয়া'),
('tamponare', 'rear-end', 'পিছন থেকে ধাক্কা দেওয়া'),
('collidere', 'collide', 'সংঘর্ষ হওয়া'),
('investire', 'run over', 'ধাক্কা দিয়ে চাপা দেওয়া'),
('rischiare', 'risk', 'ঝুঁকি নেওয়া'),
('perdere il controllo', 'lose control', 'নিয়ন্ত্রণ হারানো'),
('provocare', 'cause', 'ঘটানো'),
('causare', 'cause', 'ঘটানো'),
('prevenire', 'prevent', 'প্রতিরোধ করা'),
('assicurare', 'insure', 'বিমা করা'),
('risarcire', 'compensate', 'ক্ষতিপূরণ দেওয়া'),
('acconsentire', 'consent', 'সম্মতি দেওয়া'),
('adottare', 'adopt', 'গ্রহণ করা'),
('procedere con cautela', 'proceed with caution', 'সতর্কভাবে অগ্রসর হওয়া'),
('viscido', 'slippery', 'পিচ্ছিল'),
('sdrucciolevole', 'slippery', 'পিচ্ছিল'),
('sconnesso', 'uneven', 'অসমতল'),
('deteriorato', 'deteriorated', 'ক্ষতিগ্রস্ত'),
('danneggiato', 'damaged', 'নষ্ট'),
('ingombrante', 'bulky', 'বড় ও অস্বস্তিকর'),
('ombreggiato', 'shaded', 'ছায়াযুক্ত'),
('bagnato', 'wet', 'ভেজা'),
('allagato', 'flooded', 'জলমগ্ন'),
('fangoso', 'muddy', 'কাদাযুক্ত'),
('ghiacciato', 'icy', 'বরফাচ্ছন্ন'),
('innevato', 'snowy', 'তুষারাচ্ছন্ন'),
('visibile', 'visible', 'দৃশ্যমান'),
('invisibile', 'invisible', 'অদৃশ্য'),
('efficiente', 'efficient', 'কার্যকর'),
('inefficiente', 'inefficient', 'অকার্যকর'),
('idoneo', 'fit', 'উপযুক্ত'),
('non idoneo', 'unfit', 'অযোগ্য'),
('omologato', 'approved', 'অনুমোদিত'),
('non omologato', 'not approved', 'অননুমোদিত'),
('revisionato', 'inspected', 'পরিদর্শিত'),
('non revisionato', 'not inspected', 'অপরিদর্শিত'),
('obbligatorio', 'mandatory', 'বাধ্যতামূলক'),
('vietato', 'prohibited', 'নিষিদ্ধ'),
('consentito', 'permitted', 'অনুমোদিত'),
('temporaneo', 'temporary', 'অস্থায়ী'),
('permanente', 'permanent', 'স্থায়ী'),
('prevalente', 'prevailing', 'প্রাধান্যপ্রাপ্ত'),
('integrativo', 'supplementary', 'অতিরিক্ত'),
('apposito', 'designated', 'নির্দিষ্ট'),
('idoneamente', 'properly', 'যথাযথভাবে'),
('regolarmente', 'regularly', 'নিয়মিতভাবে'),
('impropriamente', 'improperly', 'অনুপযুক্তভাবে'),
('alternativo', 'alternative', 'বিকল্প'),
('simultaneo', 'simultaneous', 'একযোগে'),
('eventuale', 'possible', 'সম্ভাব্য'),
('eventualmente', 'if necessary', 'প্রয়োজন হলে'),
('ovvero', 'that is', 'অর্থাৎ'),
('pertanto', 'therefore', 'সুতরাং'),
('nonostante', 'despite', 'সত্ত্বেও'),
('salvo', 'unless', 'ছাড়া'),
('massimale', 'insurance cap', 'বিমা সীমা'),
('rivalsa', 'recourse', 'পুনরুদ্ধার দাবি'),
('neopatentato', 'newly licensed driver', 'নতুন লাইসেন্সধারী'),
('recidiva', 'repeat offence', 'পুনরাবৃত্ত অপরাধ'),
('aggravante', 'aggravating circumstance', 'গুরুতরকারী কারণ'),
('attenuante', 'mitigating circumstance', 'লঘুকরণকারী কারণ'),
('decadenza', 'lapse', 'মেয়াদোত্তীর্ণ'),
('sanzione amministrativa', 'administrative penalty', 'প্রশাসনিক শাস্তি'),
('sanzione accessoria', 'ancillary penalty', 'অতিরিক্ত শাস্তি'),
('responsabilita', 'liability', 'দায়বদ্ধতা'),
('responsabilita oggettiva', 'strict liability', 'বস্তুনিষ্ঠ দায়'),
('copertura', 'coverage', 'কভারেজ'),
('franchigia', 'excess', 'ডিডাক্টিবল'),
('premio', 'premium', 'প্রিমিয়াম'),
('indennizzo', 'indemnity', 'ক্ষতিপূরণ'),
('sinistro stradale', 'road accident', 'সড়ক দুর্ঘটনা'),
('contestazione', 'challenge', 'আপত্তি'),
('notifica', 'notification', 'নোটিশ'),
('deferimento', 'referral', 'প্রেরণ'),
('patteggiamento', 'plea bargain', 'সমঝোতা'),
('assunzione di alcol', 'alcohol intake', 'অ্যালকোহল সেবন'),
('alterazione', 'impairment', 'অক্ষমতা'),
('astinenza', 'withdrawal', 'উপসর্গহীনতা'),
('ebbro', 'intoxicated', 'মদ্যপ'),
('intossicato', 'intoxicated', 'বিষাক্ত'),
('psicotrope', 'psychotropic', 'মনোপ্রভাবকারী'),
('stupefacente', 'narcotic', 'মাদক'),
('farmaco', 'medicine', 'ঔষধ'),
('sedativo', 'sedative', 'সেডেটিভ'),
('stimolante', 'stimulant', 'উদ্দীপক'),
('tachicardia', 'tachycardia', 'হৃদস্পন্দন বৃদ্ধি'),
('alterazione psicofisica', 'psychophysical impairment', 'মানসিক-শারীরিক অক্ষমতা'),
('disorientato', 'disoriented', 'দিশেহারা'),
('confusione', 'confusion', 'বিভ্রান্তি'),
('svenimento', 'fainting', 'অজ্ঞান হওয়া'),
('colpo di sonno', 'micro-sleep', 'ঘুমের ঝাপটা');

-- Tricky Terms: Additional batch
INSERT INTO public.vocabulary (word_it, translation_en, translation_bn) VALUES
('accostare', 'pull over', 'পাশে থামা'),
('allontanarsi', 'move away', 'সরে যাওয়া'),
('avvicinarsi', 'approach', 'কাছে যাওয়া'),
('attraversare', 'cross', 'পার হওয়া'),
('azzerare', 'reset', 'শূন্য করা'),
('bypassare', 'bypass', 'বাইপাস করা'),
('bypassare il traffico', 'bypass traffic', 'ট্রাফিক এড়িয়ে চলা'),
('calcolare', 'calculate', 'হিসাব করা'),
('caricare', 'load', 'লোড করা'),
('scaricare', 'unload', 'আনলোড করা'),
('condurre', 'drive', 'চালনা করা'),
('custodire', 'guard', 'সংরক্ষণ করা'),
('deformare', 'deform', 'বিকৃত করা'),
('delimitare', 'delimit', 'সীমা নির্ধারণ করা'),
('denunciare', 'report', 'অভিযোগ করা'),
('detenere', 'hold', 'ধারণ করা'),
('disattivare', 'deactivate', 'নিষ্ক্রিয় করা'),
('disporre', 'arrange', 'ব্যবস্থা করা'),
('disporre di', 'have available', 'উপলব্ধ থাকা'),
('dissipare', 'dissipate', 'ছড়িয়ে দেওয়া'),
('distinguere', 'distinguish', 'পার্থক্য করা'),
('documentare', 'document', 'নথিভুক্ত করা'),
('dotare', 'equip', 'সজ্জিত করা'),
('effettuare', 'carry out', 'সম্পন্ন করা'),
('eludere', 'evade', 'এড়িয়ে যাওয়া'),
('emanare', 'issue', 'জারি করা'),
('emergere', 'emerge', 'উদ্ভূত হওয়া'),
('equipaggiare', 'equip', 'সজ্জিত করা'),
('escludere', 'exclude', 'বর্জন করা'),
('esonerare', 'exempt', 'ছাড় দেওয়া'),
('esporre', 'display', 'প্রদর্শন করা'),
('estinguere', 'extinguish', 'নেভানো'),
('fiancheggiare', 'flank', 'পাশ দিয়ে চলা'),
('garantire', 'guarantee', 'নিশ্চিত করা'),
('immettere', 'enter', 'প্রবেশ করানো'),
('immobilizzare', 'immobilise', 'অচল করা'),
('impedire', 'prevent', 'বাধা দেওয়া'),
('incrociare', 'cross', 'ছেদ করা'),
('innestare', 'engage', 'সংযুক্ত করা'),
('introdurre', 'introduce', 'প্রবর্তন করা'),
('inseguire', 'pursue', 'পিছনে ধাওয়া করা'),
('interpellare', 'consult', 'পরামর্শ নেওয়া'),
('intervenire', 'intervene', 'হস্তক্ষেপ করা'),
('intimare', 'order', 'আদেশ দেওয়া'),
('inviare', 'send', 'প্রেরণ করা'),
('lanciare', 'launch', 'নিক্ষেপ করা'),
('liberare', 'clear', 'খালি করা'),
('manomettere', 'tamper', 'ব্যবধান করা'),
('mettere in moto', 'start the engine', 'ইঞ্জিন চালু করা'),
('motivare', 'justify', 'যুক্তি দেওয়া'),
('muovere', 'move', 'সরানো'),
('obbedire', 'obey', 'মান্য করা'),
('occupare', 'occupy', 'দখল করা'),
('operare', 'operate', 'চালনা করা'),
('opporre', 'oppose', 'বিরোধিতা করা'),
('organizzare', 'organise', 'সংগঠিত করা'),
('parcheggiare', 'park', 'পার্ক করা'),
('pattugliare', 'patrol', 'টহল দেওয়া'),
('percepire', 'perceive', 'অনুভব করা'),
('perdere aderenza', 'lose grip', 'গ্রিপ হারানো'),
('pianificare', 'plan', 'পরিকল্পনা করা'),
('proteggere', 'protect', 'রক্ষা করা'),
('provvedere', 'provide', 'ব্যবস্থা করা'),
('raccogliere', 'collect', 'সংগ্রহ করা'),
('rafforzare', 'reinforce', 'শক্তিশালী করা'),
('raggiungere', 'reach', 'পৌঁছানো'),
('recedere', 'recede', 'পিছিয়ে যাওয়া'),
('reintrodurre', 'reintroduce', 'পুনঃপ্রবর্তন করা'),
('restringere', 'restrict', 'সীমিত করা'),
('riparare', 'repair', 'মেরামত করা'),
('ripristinare', 'restore', 'পুনঃস্থাপন করা'),
('riscontrare', 'find', 'পাওয়া'),
('risultare', 'result', 'ফল হওয়া'),
('ritardare', 'delay', 'বিলম্ব করা'),
('ridimensionare', 'reduce', 'আকার কমানো'),
('rinnovare', 'renew', 'নবায়ন করা'),
('rilasciare', 'issue', 'ইস্যু করা'),
('rimuovere', 'remove', 'অপসারণ করা'),
('scongiurare', 'avert', 'এড়ানো'),
('sigillare', 'seal', 'সিল করা'),
('sollevare', 'lift', 'উত্তোলন করা'),
('sopraggiungere', 'arrive suddenly', 'হঠাৎ এসে পৌঁছানো'),
('sostare', 'stay parked', 'পার্ক করে থাকা'),
('sottovalutare', 'underestimate', 'অবমূল্যায়ন করা'),
('sovraccaricare', 'overload', 'অতিরিক্ত বোঝা দেওয়া'),
('sovrapporre', 'overlap', 'আচ্ছাদিত করা'),
('sostituire', 'replace', 'প্রতিস্থাপন করা'),
('spegnere', 'switch off', 'বন্ধ করা'),
('stazionare', 'stand', 'অবস্থান করা'),
('stringere', 'tighten', 'টাইট করা'),
('tendere', 'extend', 'প্রসারিত করা'),
('transitare', 'pass through', 'চলাচল করা'),
('trasportare', 'transport', 'পরিবহন করা'),
('trattare', 'handle', 'ব্যবহার করা'),
('tutelare', 'safeguard', 'রক্ষা করা'),
('utilizzare', 'use', 'ব্যবহার করা'),
('variare', 'vary', 'পরিবর্তন করা'),
('verificare', 'verify', 'যাচাই করা'),
('vigilare', 'keep watch', 'পর্যবেক্ষণ করা'),
('volgere', 'turn', 'ঘুরানো'),
('adeguato', 'adequate', 'উপযুক্ত'),
('inadeguato', 'inadequate', 'অনুপযুক্ত'),
('visibile a distanza', 'visible from distance', 'দূর থেকে দৃশ্যমান'),
('invisibile a distanza', 'not visible from distance', 'দূর থেকে অদৃশ্য'),
('accecato', 'blinded', 'অন্ধকারাচ্ছন্ন'),
('abbagliato', 'dazzled', 'ঝলকানিতে আক্রান্ত'),
('opaco', 'opaque', 'অস্বচ্ছ'),
('trasparente', 'transparent', 'স্বচ্ছ'),
('rotto', 'broken', 'ভাঙা'),
('usurato', 'worn', 'ক্ষয়প্রাপ্ত'),
('consumato', 'worn out', 'ক্ষয়প্রাপ্ত'),
('sdrucito', 'frayed', 'ক্ষয়িষ্ণু'),
('pericoloso', 'dangerous', 'বিপজ্জনক'),
('rischioso', 'risky', 'ঝুঁকিপূর্ণ'),
('sicuro', 'safe', 'নিরাপদ'),
('insicuro', 'unsafe', 'নিরাপত্তাহীন'),
('idraulico', 'hydraulic', 'হাইড্রোলিক'),
('pneumatico', 'pneumatic', 'নিউম্যাটিক'),
('elettrico', 'electric', 'বৈদ্যুতিক'),
('termico', 'thermal', 'তাপীয়'),
('automatico', 'automatic', 'স্বয়ংক্রিয়'),
('manuale', 'manual', 'ম্যানুয়াল'),
('meccanico', 'mechanical', 'যান্ত্রিক'),
('magnetico', 'magnetic', 'চুম্বকীয়'),
('obbligatorio per legge', 'required by law', 'আইনগতভাবে বাধ্যতামূলক'),
('facoltativo', 'optional', 'ঐচ্ছিক'),
('conforme', 'compliant', 'অনুগত'),
('non conforme', 'non-compliant', 'অনুগত নয়'),
('in regola', 'in order', 'নিয়মমাফিক'),
('fuori norma', 'out of compliance', 'নিয়মবহির্ভূত'),
('regolare', 'regular', 'নিয়মিত'),
('irregolare', 'irregular', 'অনিয়মিত'),
('conseguente', 'consequent', 'ফলস্বরূপ'),
('ulteriore', 'further', 'অতিরিক্ত'),
('specifico', 'specific', 'নির্দিষ্ট'),
('generale', 'general', 'সাধারণ'),
('parziale', 'partial', 'আংশিক'),
('totale', 'total', 'সম্পূর্ণ'),
('esclusivo', 'exclusive', 'একচেটিয়া'),
('inclusivo', 'inclusive', 'অন্তর্ভুক্তিমূলক'),
('prescritto', 'prescribed', 'নির্ধারিত'),
('prescrizione', 'prescription', 'নির্দেশনা'),
('deroga', 'exemption', 'ব্যতিক্রম'),
('derogare', 'grant exemption', 'ব্যতিক্রম দেওয়া'),
('circostanza', 'circumstance', 'পরিস্থিতি'),
('condizione', 'condition', 'শর্ত'),
('condizionare', 'condition', 'শর্তসাপেক্ষ করা'),
('requisito', 'requirement', 'প্রয়োজনীয়তা'),
('requisito minimo', 'minimum requirement', 'ন্যূনতম প্রয়োজন'),
('idoneita psicofisica', 'psychophysical fitness', 'মানসিক-শারীরিক যোগ্যতা'),
('invalidita', 'disability', 'অক্ষমতা'),
('incapacita', 'incapacity', 'অক্ষমতা'),
('responsabilita solidale', 'joint liability', 'যৌথ দায়'),
('rivalsa assicurativa', 'insurance recourse', 'বিমা পুনরুদ্ধার দাবি'),
('copertura temporanea', 'temporary cover', 'অস্থায়ী কভারেজ'),
('copertura sospesa', 'suspended cover', 'স্থগিত কভারেজ'),
('decadenza della copertura', 'lapse of cover', 'কভারেজ বাতিল'),
('risoluzione', 'termination', 'সমাপ্তি'),
('risoluzione del contratto', 'contract termination', 'চুক্তি বাতিল'),
('stipula', 'policy issuance', 'নীতিপত্র ইস্যু'),
('polizza', 'policy', 'পলিসি'),
('polizza rca', 'third-party policy', 'থার্ড পার্টি পলিসি'),
('premio assicurativo', 'insurance premium', 'বিমা প্রিমিয়াম'),
('clausola', 'clause', 'ধারা'),
('clausola di esclusione', 'exclusion clause', 'বর্জন ধারা'),
('clausola di rivalsa', 'recourse clause', 'পুনরুদ্ধার ধারা'),
('mancanza', 'absence', 'অভাব'),
('mancato rispetto', 'non-compliance', 'অমান্য'),
('controllo sanitario', 'medical check', 'স্বাস্থ্য পরীক্ষা'),
('certificazione', 'certification', 'সনদায়ন'),
('esito', 'outcome', 'ফলাফল'),
('negativo', 'negative', 'নেতিবাচক'),
('positivo', 'positive', 'ইতিবাচক'),
('abuso', 'abuse', 'অপব্যবহার'),
('assunzione', 'intake', 'গ্রহণ'),
('dipendenza', 'addiction', 'আসক্তি'),
('assuefazione', 'dependence', 'অভ্যাসগত আসক্তি'),
('tolleranza', 'tolerance', 'সহনশীলতা'),
('alterato', 'impaired', 'ক্ষতিগ্রস্ত'),
('alterazione dei riflessi', 'impaired reflexes', 'প্রতিক্রিয়া ক্ষমতা হ্রাস'),
('lucidita', 'lucidity', 'সজাগতা'),
('reattivita', 'reactivity', 'প্রতিক্রিয়াশীলতা'),
('tempi di reazione allungati', 'slower reaction times', 'প্রতিক্রিয়া সময় বৃদ্ধি'),
('psicofarmaco', 'psychotropic medicine', 'মনোপ্রভাবকারী ওষুধ'),
('analgesico', 'analgesic', 'ব্যথানাশক'),
('ansiolitico', 'anxiolytic', 'উদ্বেগনাশক'),
('sonnifero', 'sleeping pill', 'ঘুমের ওষুধ'),
('confusione mentale', 'mental confusion', 'মানসিক বিভ্রান্তি'),
('stato di ebbrezza', 'state of intoxication', 'মদ্যতার অবস্থা'),
('stato di agitazione', 'state of agitation', 'উত্তেজিত অবস্থা'),
('stato di panico', 'state of panic', 'আতঙ্কিত অবস্থা'),
('stato di ansia', 'state of anxiety', 'উদ্বেগের অবস্থা'),
('stato di sonnolenza', 'state of drowsiness', 'তন্দ্রাচ্ছন্ন অবস্থা'),
('depressione', 'depression', 'বিষণ্নতা'),
('euforia', 'euphoria', 'অতিউচ্ছ্বাস'),
('suscettibile', 'susceptible', 'সংবেদনশীল'),
('compatibile', 'compatible', 'সামঞ্জস্যপূর্ণ'),
('incompatibile', 'incompatible', 'সামঞ্জস্যহীন'),
('contestabile', 'contestable', 'আপত্তিযোগ্য'),
('impugnabile', 'appealable', 'আপিলযোগ্য'),
('inappellabile', 'final', 'চূড়ান্ত'),
('inoppugnabile', 'unassailable', 'অপ্রতিদ্বন্দ্বী'),
('soggetto a', 'subject to', 'অধীন'),
('in caso di', 'in case of', 'এর ক্ষেত্রে'),
('a condizione che', 'provided that', 'শর্তে'),
('a meno che', 'unless', 'যদি না'),
('qualora', 'in the event that', 'যদি ঘটে'),
('fatti salvi', 'without prejudice to', 'অক্ষুণ্ণ রেখে'),
('entro', 'within', 'মধ্যে'),
('oltre', 'beyond', 'ছাড়িয়ে'),
('prima di', 'before', 'আগে'),
('dopo', 'after', 'পরে'),
('in prossimita', 'in proximity', 'কাছাকাছি'),
('in corrispondenza', 'at', 'সংলগ্ন স্থানে'),
('in assenza', 'in absence', 'অনুপস্থিতিতে'),
('in presenza', 'in presence', 'উপস্থিতিতে'),
('secondo', 'according to', 'অনুযায়ী'),
('ai fini di', 'for the purpose of', 'উদ্দেশ্যে'),
('a norma di', 'pursuant to', 'অনুযায়ী'),
('ai sensi di', 'under', 'এর অধীনে'),
('reiterazione', 'repetition', 'পুনরাবৃত্তি'),
('fuga', 'flight', 'পলায়ন'),
('omissione di soccorso', 'failure to render assistance', 'সহায়তা না করা'),
('responsabilita del conducente', 'driver liability', 'চালকের দায়'),
('responsabilita del proprietario', 'owner liability', 'মালিকের দায়');

-- Tricky Terms: Additional batch 2 (unique terms)
INSERT INTO public.vocabulary (word_it, translation_en, translation_bn) VALUES
('ottemperare', 'comply', 'মান্য করা'),
('ottemperanza', 'compliance', 'মান্যতা'),
('attuare', 'implement', 'বাস্তবায়ন করা'),
('applicarsi', 'apply oneself', 'মনোযোগ দেওয়া'),
('accendere', 'switch on', 'চালু করা'),
('spegnersi', 'switch off', 'বন্ধ হওয়া'),
('avvertire', 'warn', 'সতর্ক করা'),
('informare', 'inform', 'অবহিত করা'),
('istruire', 'instruct', 'নির্দেশ দেওয়া'),
('prescrivere', 'prescribe', 'নির্দেশ করা'),
('indicarsi', 'be indicated', 'উল্লেখ থাকা'),
('escludersi', 'be excluded', 'বর্জিত থাকা'),
('implicare', 'entail', 'ইঙ্গিত করা'),
('imporsi', 'be required', 'বাধ্যতামূলক হওয়া'),
('riprendere', 'resume', 'পুনরায় শুরু করা'),
('ripartire', 'set off again', 'পুনরায় যাত্রা করা'),
('sorpassare in sicurezza', 'overtake safely', 'নিরাপদে ওভারটেক করা'),
('sorpasso vietato', 'overtaking prohibited', 'ওভারটেক নিষিদ্ধ'),
('sterzare', 'steer', 'স্টিয়ারিং ঘোরানো'),
('premere', 'press', 'চাপ দেওয়া'),
('rilasciare', 'release', 'ছেড়ে দেওয়া'),
('dosare', 'modulate', 'নিয়ন্ত্রিতভাবে দেওয়া'),
('innestare la marcia', 'engage gear', 'গিয়ার লাগানো'),
('disinnestare', 'disengage', 'ছাড়িয়ে দেওয়া'),
('inserire', 'insert', 'সেট করা'),
('disinserire', 'disengage', 'বাতিল করা'),
('innalzare', 'raise', 'উঁচু করা'),
('abbassare', 'lower', 'নিচু করা'),
('stabilizzare', 'stabilise', 'স্থিতিশীল করা'),
('bilanciare', 'balance', 'ভারসাম্য করা'),
('riallineare', 'realign', 'পুনঃসামঞ্জস্য করা'),
('rialzare', 'raise again', 'পুনরায় উঁচু করা'),
('riscaldare', 'warm up', 'উষ্ণ করা'),
('raffreddare', 'cool', 'শীতল করা'),
('lubrificare', 'lubricate', 'তেল দেওয়া'),
('usare prudenza', 'use caution', 'সতর্কতা ব্যবহার করা'),
('prestare attenzione', 'pay attention', 'মনোযোগ দেওয়া'),
('agire con cautela', 'act with caution', 'সতর্কভাবে কাজ করা'),
('rinunciare', 'refrain', 'বিরত থাকা'),
('sottoscrivere', 'subscribe', 'স্বাক্ষর করা'),
('stipulare', 'enter into', 'চুক্তি করা'),
('annullare', 'cancel', 'বাতিল করা'),
('interdire', 'ban', 'নিষিদ্ধ করা'),
('derivare', 'derive', 'উৎপন্ন হওয়া'),
('constatare', 'establish', 'নিশ্চিত করা'),
('accorgersi', 'notice', 'খেয়াল করা'),
('ritenere', 'consider', 'বিবেচনা করা'),
('valutare', 'assess', 'মূল্যায়ন করা'),
('adottare misure', 'adopt measures', 'ব্যবস্থা গ্রহণ করা'),
('pattugliare un tratto', 'patrol a stretch', 'একটি অংশ টহল দেওয়া'),
('acquisire', 'acquire', 'অর্জন করা'),
('convalidare', 'validate', 'বৈধ করা'),
('ratificare', 'ratify', 'অনুমোদন করা'),
('legittimare', 'legitimise', 'বৈধতা দেওয়া'),
('revocabile', 'revocable', 'বাতিলযোগ্য'),
('irrevocabile', 'irrevocable', 'অবাতিলযোগ্য'),
('sconnesso', 'uneven', 'অসমতল'),
('dissestato', 'rough', 'অসামান্য'),
('accidentato', 'rough', 'খুব অসমতল'),
('scivoloso', 'slippery', 'পিচ্ছিল'),
('sdruccioloso', 'slippery', 'পিচ্ছিল'),
('sdrucciolare', 'slip', 'পিছলানো'),
('drenante', 'draining', 'পানি নিষ্কাশনযোগ্য'),
('impermeabile', 'waterproof', 'জলরোধী'),
('permeabile', 'permeable', 'জলভেদ্য'),
('illuminato', 'lit', 'আলোকিত'),
('male illuminato', 'poorly lit', 'অপর্যাপ্ত আলো'),
('acustico', 'audible', 'শ্রাব্য'),
('visivo', 'visual', 'চাক্ষুষ'),
('presente', 'present', 'উপস্থিত'),
('assente', 'absent', 'অনুপস্থিত'),
('integro', 'intact', 'অক্ষত'),
('deteriorabile', 'perishable', 'ক্ষয়যোগ্য'),
('efficace', 'effective', 'কার্যকর'),
('inefficace', 'ineffective', 'অকার্যকর'),
('insufficiente', 'insufficient', 'অপর্যাপ্ত'),
('sufficiente', 'sufficient', 'যথেষ্ট'),
('precaro', 'precarious', 'ঝুঁকিপূর্ণ'),
('stabile', 'stable', 'স্থিতিশীল'),
('instabile', 'unstable', 'অস্থিতিশীল'),
('regolare', 'regular', 'নিয়মিত'),
('irregolare', 'irregular', 'অনিয়মিত'),
('ordinario', 'ordinary', 'সাধারণ'),
('straordinario', 'extraordinary', 'অসাধারণ'),
('temporaneo', 'temporary', 'অস্থায়ী'),
('permanente', 'permanent', 'স্থায়ী'),
('intermittente', 'intermittent', 'বিচ্ছিন্ন'),
('continuo', 'continuous', 'অবিচ্ছিন্ন'),
('graduale', 'gradual', 'ধীরে ধীরে'),
('immediato', 'immediate', 'তাৎক্ষণিক'),
('successivo', 'subsequent', 'পরবর্তী'),
('contestuale', 'simultaneous', 'একসাথে'),
('minimo', 'minimum', 'ন্যূনতম'),
('massimo', 'maximum', 'সর্বোচ্চ'),
('parziale', 'partial', 'আংশিক'),
('totale', 'total', 'সম্পূর্ণ'),
('preferenziale', 'preferential', 'অগ্রাধিকারমূলক'),
('prioritario', 'priority', 'অগ্রাধিকারমূলক'),
('sanzione pecuniaria', 'financial penalty', 'আর্থিক জরিমানা'),
('pena accessoria', 'ancillary penalty', 'অতিরিক্ত দণ্ড'),
('misura cautelare', 'precautionary measure', 'সতর্কতামূলক ব্যবস্থা'),
('misura preventiva', 'preventive measure', 'প্রতিরোধমূলক ব্যবস্থা'),
('obbligo di custodia', 'duty of custody', 'হেফাজতের বাধ্যবাধকতা'),
('obbligo di denuncia', 'duty to report', 'অভিযোগের বাধ্যবাধকতা'),
('responsabilita condivisa', 'shared liability', 'যৌথ দায়'),
('responsabilita contrattuale', 'contractual liability', 'চুক্তিগত দায়'),
('responsabilita extracontrattuale', 'tort liability', 'চুক্তিবহির্ভূত দায়'),
('inadempienza', 'non-fulfilment', 'অমান্যতা'),
('inadempimento', 'default', 'চুক্তি লঙ্ঘন'),
('danno materiale', 'material damage', 'বস্তুগত ক্ষতি'),
('danno personale', 'personal injury', 'ব্যক্তিগত ক্ষতি'),
('danno a terzi', 'third-party damage', 'তৃতীয় পক্ষের ক্ষতি'),
('responsabilita verso terzi', 'third-party liability', 'তৃতীয় পক্ষের দায়'),
('clausola vessatoria', 'onerous clause', 'অন্যায্য ধারা'),
('franchigia obbligatoria', 'mandatory excess', 'বাধ্যতামূলক ডিডাক্টিবল'),
('premio ridotto', 'reduced premium', 'কম প্রিমিয়াম'),
('premio maggiorato', 'increased premium', 'বাড়তি প্রিমিয়াম'),
('regolarizzazione', 'regularisation', 'নিয়মিতকরণ'),
('rinnovo', 'renewal', 'নবায়ন'),
('riabilitazione', 'rehabilitation', 'পুনর্বাসন'),
('medicinale', 'medicinal', 'ঔষধি'),
('terapeutico', 'therapeutic', 'চিকিৎসাগত'),
('effetto collaterale', 'side effect', 'পার্শ্বপ্রতিক্রিয়া'),
('interazione', 'interaction', 'পারস্পরিক ক্রিয়া'),
('controindicazione', 'contraindication', 'বিরোধ নির্দেশ'),
('intolleranza', 'intolerance', 'অসহিষ্ণুতা'),
('disidratazione', 'dehydration', 'পানিশূন্যতা'),
('ipoglicemia', 'hypoglycaemia', 'হাইপোগ্লাইসেমিয়া'),
('ipotensione', 'hypotension', 'নিম্ন রক্তচাপ'),
('ipertensione', 'hypertension', 'উচ্চ রক্তচাপ'),
('vertigine', 'vertigo', 'মাথা ঘোরা'),
('nausea', 'nausea', 'বমিভাব'),
('crampo', 'cramp', 'পেশী খিঁচুনি'),
('cefalea', 'headache', 'মাথাব্যথা'),
('intontimento', 'dizziness', 'ঝিমঝিম ভাব'),
('offuscamento visivo', 'blurred vision', 'দৃষ্টি ঝাপসা'),
('disturbo dell equilibrio', 'balance disorder', 'ভারসাম্য সমস্যায়'),
('ansimare', 'pant', 'হাঁপানো'),
('agitazione', 'agitation', 'অস্থিরতা'),
('reattivita ridotta', 'reduced responsiveness', 'প্রতিক্রিয়া কমে যাওয়া'),
('prontezza', 'readiness', 'সতর্ক প্রস্তুতি'),
('lucidita mentale', 'mental clarity', 'মানসিক সজাগতা'),
('capacita percettiva', 'perceptual ability', 'অনুভবক্ষমতা'),
('condizione psicofisica', 'psychophysical condition', 'মানসিক-শারীরিক অবস্থা'),
('stato psicofisico', 'psychophysical state', 'মানসিক-শারীরিক অবস্থা');
